### ISSUE TITLE
Failded in install on ARM Mac

### ISSUE THREAD

**Issue by kodragonP** [Yasas1994/Jaeger#12]
The installation faild at the last step! It seems like that there is something wrong in building autotools.
```
configuring m4
      running ./configure --prefix=/private/var/folders/85/1bvfjr015994z70shl4b1_xc0000gn/T/pip-install-zf61w6b8/parasail_eb23eb464f0f4161a473ed00471d5a35/autotools CPPFLAGS=-D_IO_IN_BACKUP=0x100
      b"checking for a BSD-compatible install... /usr/bin/install -c\nchecking whether build environment is sane... yes\nchecking for a thread-safe mkdir -p... build-aux/install-sh -c -d\nchecking for gawk... no\nchecking for mawk... no\nchecking for nawk... no\nchecking for awk... awk\nchecking whether make sets $(MAKE)... no\nchecking whether make supports nested variables... no\nchecking for gcc... gcc\nchecking whether the C compiler works... no\nconfigure: error: in `/private/var/folders/85/1bvfjr015994z70shl4b1_xc0000gn/T/pip-install-zf61w6b8/parasail_eb23eb464f0f4161a473ed00471d5a35/autotools/m4-1.4.17':\nconfigure: error: C compiler cannot create executables\nSee `config.log' for more details\n"
      configure of m4 failed
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/85/1bvfjr015994z70shl4b1_xc0000gn/T/pip-install-zf61w6b8/parasail_eb23eb464f0f4161a473ed00471d5a35/setup.py", line 515, in <module>
          setup(
        File "/opt/miniconda3/envs/jaeger/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/opt/miniconda3/envs/jaeger/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/opt/miniconda3/envs/jaeger/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/opt/miniconda3/envs/jaeger/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/miniconda3/envs/jaeger/lib/python3.9/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/opt/miniconda3/envs/jaeger/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/85/1bvfjr015994z70shl4b1_xc0000gn/T/pip-install-zf61w6b8/parasail_eb23eb464f0f4161a473ed00471d5a35/setup.py", line 488, in run
          prepare_shared_lib()
        File "/private/var/folders/85/1bvfjr015994z70shl4b1_xc0000gn/T/pip-install-zf61w6b8/parasail_eb23eb464f0f4161a473ed00471d5a35/setup.py", line 470, in prepare_shared_lib
          build_parasail(libname)
        File "/private/var/folders/85/1bvfjr015994z70shl4b1_xc0000gn/T/pip-install-zf61w6b8/parasail_eb23eb464f0f4161a473ed00471d5a35/setup.py", line 338, in build_parasail
          raise RuntimeError("building autotools failed")
      RuntimeError: building autotools failed
```

**Comment by Yasas1994** [comment]
Hi @kodragonP,

Thanks for trying out Jaeger and reporting this issue.

I will get back to you with a fix soon!

**Comment by Yasas1994** [comment]
Hi @kodragonP ,

Its ready now! 

however, you will have to install jaeger following these steps. 

```
  # create a conda environment
  conda create -c conda-forge -c apple -c bioconda -c defaults -n jaeger python=3.9 pip

  # clone the git repository
  git clone https://github.com/Yasas1994/Jaeger.git

  # install jaeger
  cd Jaeger
  pip install .
```
I will update the PyPi and bioconda versions with these changes but this will take some time :)
